### ISSUE TITLE
Plugin doesn't open my vault in VS Code

### ISSUE THREAD

**Issue by kenanmike** [NomarCub/obsidian-open-vscode#3]
I've downloaded and enabled the plugin, but when I either click the ribbon or select command from the command palette, Obsidian freezes for a couple of seconds then nothing happens. 
I'm on MacOS Big Sur 11.4, using the latest version of Obsidian and the latest version of the plugin. VS Code itself works fine for me.

**Comment by NomarCub** [comment]
I don't have a mac to test on, so please help me out here.

Have you tried the URL option?
What happens when you use a shell outside of Obsidian to launch VSCode with the vault (`code {{vault path}}`)?
If you open the developer view in Obsidian (Ctrl + Shift + I on Windows), do you see an error log?

**Comment by kenanmike** [comment]
Yes, URL works! Thanks. As far I’m concerned there’s no issue now. 
But to answer you directly, after putting the vault path, using the shell doesn’t work, and there’s no errors in my error log strangely.
As I said, though, URL works great, and on Mac first time you can even not to get asked again whether to open it, so it works lightning fast now.

**Comment by NomarCub** [comment]
Glad it works now!
If more people have this issue, I'll probably update the readme to make things clearer, and set the URL method as default.

**Comment by andynameistaken** [comment]
Yeah, bumped at this issue too. If you are working on Linux you can always check `sosumi` for mac testing

**Comment by NomarCub** [comment]
Thanks for the recommendation.
Did you have the same issue, and resolved it with the URL method too?

**Comment by huyz** [comment]
I have the same problem with macOS 11.5.  But I can't switch to the URL method because I'm trying to open a Dendron workspace, which requires that I use the command: `code "{{vaultpath}}/../dendron.code-workspace"` to work.

**Comment by NomarCub** [comment]
Does the command (with vaultpath substituted) work in a normal shell?

If not I could make some modifications with more logging to send you.

**Comment by huyz** [comment]
The command in the shell does work. I go to the vault and run: `code "$PWD/../dendron.code-workspace"`

Sure, I can take your mods

**Comment by NomarCub** [comment]
Here's a modified main.js with more logging.

This plugin uses Node.js `child_process` to execute, which I know nothing about, so I may not be able to offer a timely solution or any.

[main.zip](https://github.com/NomarCub/obsidian-open-vscode/files/7288272/main.zip)

**Comment by huyz** [comment]
Thanks, that extra logging didn't help but you pointed me to the code where I could add my own logging. It turns out that we needed the full path of `code`.

So this worked: `/usr/local/bin/code "{{vaultpath}}/../dendron.code-workspace"`
I don't know why `/usr/local/bin` isn't in the `$PATH` for Obsidian on macOS.

Btw, this is the debugging code that helped me figure it out, which you may want to add to your code:
```js
              const execResult = exec(command, (error, stdout, stderr) => {
                if (error) {
                  console.error(`exec error: ${error}`);
                  return;
                }
              });
```

**Comment by NomarCub** [comment]
I'm glad it works, and thanks for the tip!
I made a new release adding this, I hope it can help others in the future as well.

**Comment by kyan001** [comment]
I got this working on both macOS and Windows.

Since I need to sync the plugin settings across platforms, I needed a universal 'code' command. Neither `code ...` nor `/usr/local/bin/code ...` worked on both consistently. I ended up using this on "Template for executing the 'code' command": 

```Shell
code "{{vaultpath}}/{{filepath}}" || open -a "Visual Studio Code" "{{vaultpath}}/{{filepath}}"
```
If the first command fails on macOS, it falls back to opening the VS Code App as the command. I've tested this on both macOS and Win11, and it works perfectly.

***

Btw, I use the `vscode://` URL for the ribbon button to open the entire vault in VS Code. The "Open in VS Code" option is specifically for files and folders, which is why I only pass the file path to the command instead of the vault root.

**Comment by NomarCub** [comment]
Thanks for the info!
I recently added a more lengthy readme section about this [here](https://github.com/NomarCub/obsidian-open-vscode?tab=readme-ov-file#prerequisites). Maybe the [VS Code docs link](https://code.visualstudio.com/docs/setup/mac#_launch-vs-code-from-the-command-line) there could also help you do a simpler workaround.
